[versions]
agp = "8.10.1"
androidx_arch_core_core_testing = "2.2.0"
androidx_activity_activity_ktx = "1.11.0"
androidx_appcompat_appcompat = "1.7.1"
androidx_constraintlayout_constraintlayout = "2.2.1"
androidx_core_core_ktx = "1.16.0"
androidx_fragment_fragment_ktx = "1.8.9"
androidx_lifecycle = "2.10.0"
androidx_recyclerview_recyclerview = "1.4.0"
androidx_recyclerview_recyclerview_selection = "1.1.0"
androidx_room = "2.8.4"
androidx_test_core_ktx = "1.6.1"
androidx_test_espresso = "3.7.0"
androidx_test_ext_junit = "1.2.1"
com_google_android_material_material = "1.13.0"
junit_junit = "4.13.2"
kotlin = "2.2.21"
kspVersion = "2.2.21-2.0.5"
org_jetbrains_kotlinx_kotlinx_coroutines_test = "1.10.2"
org_mockito_kotlin_mockito_kotlin = "5.4.0"
org_robolectric_robolectric = "4.16.1"

[libraries]
androidx-arch-core-core-testing = {  group = "androidx.arch.core", name = "core-testing", version.ref = "androidx_arch_core_core_testing" }
androidx-activity-activity-ktx = {  group = "androidx.activity", name = "activity-ktx", version.ref = "androidx_activity_activity_ktx" }
androidx-appcompat-appcompat = {  group = "androidx.appcompat", name = "appcompat", version.ref = "androidx_appcompat_appcompat" }
androidx-constraintlayout-constraintlayout = {  group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx_constraintlayout_constraintlayout" }
androidx-core-core-ktx = {  group = "androidx.core", name = "core-ktx", version.ref = "androidx_core_core_ktx" }
androidx-fragment-fragment-ktx = {  group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx_fragment_fragment_ktx" }
androidx-lifecycle-lifecycle-livedata-ktx = {  group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidx_lifecycle" }
androidx-lifecycle-lifecycle-runtime-ktx = {  group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx_lifecycle" }
androidx-lifecycle-lifecycle-runtime-testing = {  group = "androidx.lifecycle", name = "lifecycle-runtime-testing", version.ref = "androidx_lifecycle" }
androidx-lifecycle-lifecycle-viewmodel-ktx = {  group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx_lifecycle" }
androidx-recyclerview-recyclerview = {  group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx_recyclerview_recyclerview" }
androidx-recyclerview-recyclerview-selection = {  group = "androidx.recyclerview", name = "recyclerview-selection", version.ref = "androidx_recyclerview_recyclerview_selection" }
androidx-room-room-compiler = {  group = "androidx.room", name = "room-compiler", version.ref = "androidx_room" }
androidx-room-room-ktx = {  group = "androidx.room", name = "room-ktx", version.ref = "androidx_room" }
androidx-room-room-runtime = {  group = "androidx.room", name = "room-runtime", version.ref = "androidx_room" }
androidx-room-room-testing = {  group = "androidx.room", name = "room-testing", version.ref = "androidx_room" }
androidx-test-core-ktx = {  group = "androidx.test", name = "core-ktx", version.ref = "androidx_test_core_ktx" }
androidx-test-espresso-espresso-contrib = {  group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "androidx_test_espresso" }
androidx-test-espresso-espresso-core = {  group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx_test_espresso" }
androidx-test-ext-junit = {  group = "androidx.test.ext", name = "junit", version.ref = "androidx_test_ext_junit" }
com-google-android-material-material = {  group = "com.google.android.material", name = "material", version.ref = "com_google_android_material_material" }
org-mockito-kotlin-mockito-kotlin = {  group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "org_mockito_kotlin_mockito_kotlin" }
junit-junit = {  group = "junit", name = "junit", version.ref = "junit_junit" }
org-jetbrains-kotlin-kotlin-stdlib = {  group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
org-jetbrains-kotlinx-kotlinx-coroutines-test = {  group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "org_jetbrains_kotlinx_kotlinx_coroutines_test" }
org-robolectric-robolectric = {  group = "org.robolectric", name = "robolectric", version.ref = "org_robolectric_robolectric" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
