name: Continuous Integration
on: push

jobs:
  buildTestDeploy:
    name: Build Test Deploy
    runs-on: ubuntu-latest
    container:
      image: alpine
      options: --user 3000
    steps:
      - run: id -u
      - name: checkout
        uses: actions/checkout@v2.3.3
      - name: trivial
        run: |
          ls