name: Continuous Integration
on: push

jobs:
  test:
    if: github.ref != 'refs/heads/master'
    name: Test
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Tests
        uses: reactivecircus/android-emulator-runner@v2.11.0
        with:
          api-level: 29
          script: |
            ./gradlew test
            ./gradlew connectedAndroidTest
      - name: Archive Tests results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          path: |
            app/build/reports/androidTests/connected
            app/build/reports/tests
          retention-days: 7

  testDeploy:
    if: github.ref != 'refs/heads/master'
    name: Test Deploy
    runs-on: ubuntu-latest
    container:
      image: circleci/android:api-30
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Unit Tests
        run: ./gradlew test
      - name: Bundle
        run: ./gradlew bundleRelease
      - name: Archive Tests results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          path: |
            app/build/reports/androidTests/connected
            app/build/reports/tests
          retention-days: 7
