name: Continuous Integration Workflow
on: push

jobs:
  test:
    runs-on: macos-10.15
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Tests
        uses: reactivecircus/android-emulator-runner@v2.11.0
        with:
          api-level: 30
          script: ./gradlew connectedCheck

