name: Continuous Integration
on: push

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.3
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2.11.0
        with:
          api-level: 29
          script: ./gradlew connectedCheck
