name: Continuous Integration
on: push

jobs:
  test:
    runs-on: macos-10.15
    steps:
      - name: Tests
        uses: reactivecircus/android-emulator-runner@v2.11.0
        with:
          api-level: 29
          script: ./gradlew connectedCheck
