name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4
      - name: Unit Tests
        run: ./gradlew test
      - name: Prepare signing upload key
        env:
          SIGNING_UPLOAD_KEY_JKS_DIR: ${{ runner.temp }}/keys
          SIGNING_UPLOAD_KEY_JKS_PATH: ${{ runner.temp }}/keys/upload.jks
        run: |
          mkdir -p "$SIGNING_UPLOAD_KEY_JKS_DIR"
          echo ${{ secrets.SIGNING_UPLOAD_KEY_JKS_BASE64 }} > "$SIGNING_UPLOAD_KEY_JKS_PATH.base64"
          base64 --decode "$SIGNING_UPLOAD_KEY_JKS_PATH.base64" > "$SIGNING_UPLOAD_KEY_JKS_PATH"
          rm -f "$SIGNING_UPLOAD_KEY_JKS_PATH.base64"
      - name: Bundle
        env:
          SIGNING_UPLOAD_KEY_JKS_PATH: ${{ runner.temp }}/keys/upload.jks
          SIGNING_UPLOAD_KEY_PASSWORD: ${{ secrets.SIGNING_UPLOAD_KEY_PASSWORD }}
        run: |
          ./gradlew bundleRelease
          rm -f "$SIGNING_UPLOAD_KEY_JKS_PATH"
      - name: Ensure signing upload keys are erased
        if: ${{ always() }}
        env:
          SIGNING_UPLOAD_KEY_JKS_PATH: ${{ runner.temp }}/keys/upload.jks
        run: |
          rm -f "$SIGNING_UPLOAD_KEY_JKS_PATH.base64"
          rm -f "$SIGNING_UPLOAD_KEY_JKS_PATH"
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: python -m pip install --requirement requirements.txt
      - uses: 'google-github-actions/auth@v3'
        with:
          workload_identity_provider: 'projects/727006907851/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'publishgoogleplay@pc-api-9058766712512086413-546.iam.gserviceaccount.com'
      - name: Deploy
        run: python release_to_google_play.py
